### ISSUE TITLE
请问这个计算器怎么打开？

### ISSUE THREAD

**Issue by nj005py** [xianlechuanshuo/fgo#2]
大佬，求问这个计算器怎么打开？我就在GitHub上输入了fgo顺着翻的，点开大佬的这个项目后，发现没找到入口网址，我就直接把项目下载到本地，点开看，发现用不了。
ps:
我也写了个Android版的计算器https://github.com/nj005py/FGOcalc，如果可以的话，计算中的有些问题希望可以讨论讨论。

**Comment by windybirth** [comment]
在线这个地址可以进去https://xianlechuanshuo.github.io/fgo/

**Comment by xianlechuanshuo** [comment]
可以看看这个帖子：http://bbs.nga.cn/read.php?tid=11783224，我在nga有发帖的，nga也是叫xianlechuanshuo
